config/routes.rb
Dailyphoto::Application.routes.draw do
  scope '(:locale)' do

    resources :categories
    get "photos/liked", to: "photos#favorite", :as => :liked_photos
    get "photos/random", to: "photos#random", :as => :random_photos
    resources :photos do
      member do
        post :like
      end
    end

    root :to => "photos#index"

    devise_for :users, :controllers => {:registrations => "registrations"}
    resources :users
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :category
	belongs_to :user

	has_many :likes, :dependent => :destroy
 	
 	mount_uploader :attachment, AttachmentUploader
	validates :title, presence: true

	def self.find_best(d)
		self.where(day:d).order('photos.likes_count DESC').first
	end

	def self.find_best_by_category(d, id)
		self.where(day:d).where(category_id:id).order('photos.likes_count DESC').first
	end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	before_filter :authenticate_user!, :except => [:index, :show]

	def index
		@photo = Photo.all
		@date = params[:date] ? Date.parse(params[:date]) : Date.today
		
	end

	def new
		@photo = Photo.new
	end

	def show
		@photo = Photo.find(params[:id])
	end

	def random
		@photo = Photo.all.sample
    render layout: false
	end

	def favorite
	
	end

	def like
		@photo = Photo.find(params[:id])
		
		if user_signed_in?
			@like = Like.new
			@like.user = current_user
    	@like.photo = @photo
    	if current_user.likes.where(photo:@photo).count == 0
    		@like.save
    	end
    	@photo.likes_count = @photo.likes.count
    	@photo.save
    			
    end

    render json: {count: @photo.likes.count}
	end

	def create
		@photo = Photo.new(photo_params)
		
		@photo.user = current_user
	    respond_to do |format|
	      if @photo.save
	        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
	        FilmMailer.new(@photo, current_user).deliver
	        format.json { render action: 'show', status: :created, location: @photo }
	      else
	        format.html { render action: 'new' }
	        format.json { render json: @photo.errors, status: :unprocessable_entity }
	      end
	    end
	end

	private
	def photo_params
		params.require(:photo).permit(:title, :description, :attachment, :day, :category_id)
	end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/favorite.html.erb
<div id="randomholder"><div id="random_photo"></div></div><br>
<%= link_to (t :random_photo), random_photos_path, remote: true, class: "remote_link", data:{type: 'html'}  %>

<% current_user.likes.each do |like| %>
	<%= image_tag like.photo.attachment.thumb.url %>
<% end %>



app/views/photos/index.html.erb
<%-date = @date || Date.today %>
<%-next_month_link = link_to I18n.l((date >> 1), format: "%B %Y"), {date: date >> 1}%>
<%-prev_month_link = link_to I18n.l((date << 1), format: "%B %Y"), {date: date << 1}%>
<%= calendar(:year => date.year, :month => date.month, calendar_title: I18n.l(date, format: "%B %Y"), :next_month_text=>next_month_link, :previous_month_text => prev_month_link) do |d| 

	topphoto = Photo.find_best(d)

	if topphoto
		link = link_to raw("<div style='background-image: url(#{topphoto.attachment_url(:thumb)}); width:170px; height:170px;'><span>#{topphoto.likes.count}</span></div>"), topphoto
		 [link, {}]
	else
 		[d.day, {}]
 	end

end %>

app/views/photos/new.html.erb
<div class="photo_form">
  <%= simple_form_for @photo, html: {role:"form"} do |f| %>

    <%= f.input :title %>

    <%= f.input :description %>

    <%= f.association :category, collection: Category.all.map{|el|[el.title, el.id]}, :prompt => 'Please select category' %>

    <%= f.input :attachment, as: :file, :label => "Photo" %>

    <%= f.input :day, as: :date, :discard_hour => true %>

    <%= f.button :submit %>
    
  <% end %>
</div>

app/views/photos/random.html.erb
<%= image_tag @photo.attachment.thumb %>

app/views/photos/show.html.erb

<div id="photoshow">
	<h2><%= @photo.title %></h2>
	<%= image_tag @photo.attachment %>
	<p>
		<%= @photo.description %>
	</p>

	<% if user_signed_in? %>
		<div id="likebox">
			<%= link_to image_tag("like.png", :id => "like"), like_photo_path(@photo), method: :post, remote: true, class: "like-link" %>
			<span><%= @photo.likes.count %></span>
		</div>
	<% end %>
</div>