config/routes.rb
Dailyphoto::Application.routes.draw do
  scope '(:locale)' do

    resources :categories
    get "photos/liked", to: "photos#favorite", :as => :liked_photos
    get "photos/random", to: "photos#random", :as => :random_photos
    resources :photos do
      member do
        post :like
      end
    end

    root :to => "photos#index"

    devise_for :users, :controllers => {:registrations => "registrations"}
    resources :users
  end
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to (t :home), root_path, class: 'navbar-brand' %>

    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>


	<% if user_signed_in? %>
	  <li><%= link_to (t :edit_account), edit_user_registration_path %></li>
	<% end %>

	<% if user_signed_in? %>
	  <li><%= link_to (t :favorite_photos), liked_photos_path %></li>
	<% end %>

	<% if user_signed_in? %>
	  <li><%= link_to (t :logout), destroy_user_session_path, :method=>'delete' %></li>
	<% else %>
	  <li><%= link_to (t :login), new_user_session_path %></li>
	  <li><%= link_to (t :sign_up), new_user_registration_path %></li>
	<% end %>

	
		<li><%= link_to (image_tag "uk.png"), {locale: "uk"} %></li> 
	
		<li><%= link_to (image_tag "en.png"), {locale: "en"} %></li>
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Dailyphoto" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Dailyphoto" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>

      <ul class="nav nav-tabs nav-justified">
        <li class="<%= 'active' if params[:id] == 'Nature' %>">
          <%= link_to (t :nature), category_path(Category.find_by(title: "Nature")) %>
        </li>
        <li class="<%= 'active' if params[:id] == 'Sport' %>">
          <%= link_to (t :sport), category_path(Category.find_by(title: "Sport")) %>
        </li>
        <li class="<%= 'active' if params[:id] == 'Breaking News' %>">
          <%= link_to (t :breaking_news), category_path(Category.find_by(title: "Breaking News")) %>
        </li>
        <li class="<%= 'active' if params[:id] == 'Funny' %>">
          <%= link_to (t :funny), category_path(Category.find_by(title: "Funny")) %>
        </li>
      </ul>
    
    <main role="main" class="container">
      <%= render 'layouts/messages' %>
        
          <%= yield %> 
        
    </main>
  </body>
</html>